# Generated by Django 4.2.3 on 2023-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_annomalie_stock_order_date_livraison_predite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='annomalie_stock',
            field=models.IntegerField(null=True),
        ),
    ]
