# Generated by Django 4.2.3 on 2023-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_annomalie_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='annomalie_stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
