# Generated by Django 4.2.3 on 2023-10-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_annomalie_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_CountryCode', models.CharField(max_length=255)),
                ('vendor_poste', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_dimension',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vendordimension'),
        ),
    ]
