# Generated by Django 4.2.3 on 2023-10-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendordimension_order_vendor_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor_dimension',
        ),
        migrations.DeleteModel(
            name='VendorDimension',
        ),
    ]
