# Generated by Django 4.2.3 on 2023-10-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_vendor_dimension_delete_vendordimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='etat_stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
